require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Layout/LineLength:
  Enabled: false
  Max: 120

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Max: 1000

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 100

Metrics/PerceivedComplexity:
  Max: 20

Minitest/AssertPredicate:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  AllowInnerSlashes: true
